
var questions = [{question: "What percent of the United States is underneath the oceans?",
                    choices: ["A: 40%","B: 50%", "C: 60%", "D: 70"],
                    correctAnswer: "50%"},
                   {question: "Over what percent of our planet's oxygen levels are produced by the ocean?",
                    choices: ["A: Over 50%", "B: Over 60%", "C: Over 70%", "D: Over 80%"],
                    correctAnswer: "Over 70%"},
                   {question: "About how many islands does the Pacific Ocean contain?",
                    choices: ["A: 25,000", "B: 30,000", "C: 40,000", "D: 7"],
                    correctAnswer: "25,000"},
                   {question: "How many people have set foot on the Mariana Trench (lowest point in the ocean)?",
                    choices: ["A: 1", "B: 2", "C: 3", "D: 4"],
                    correctAnswer: "3"},
                   {question: "About how many shipwrecks are in the oceans?",
                    choices: ["A: 3,000,000", "B: 4,000,000", "C: 5,000,000", "D: 6,000,000"],
                    correctAnswer: "3,000,000"},
                   {question: "How deep is the Mariana Trench?",
                    choices: ["A: 6 miles", "B: 6.5 miles", "C: 7 miles", "D: 7.5 miles"],
                    correctAnswer: "7 miles"},
                   {question: "How long was the largest blue whale ever recorded?",
                    choices: ["A: 108 feet", "B: 118 feet", "C: 128 feet", "D: 138 feet"],
                    correctAnswer: "108 feet"},
                   {question: "What is the largest ocean on Earth?",
                    choices: ["A: Atlantic", "B: Indian", "C: Asian", "D: Pacific"],
                    correctAnswer: "Pacific"},
                   {question: "What is the average depth of the ocean?",
                    choices: ["A: 11,100 feet", "B: 12,100 feet", "C: 13,100 feet", "D: 14,100 feet"],
                    correctAnswer: "12,100 feet"},
                   {question: "Where was the world record for deepest freedive set?",
                    choices: ["A: Russia", "B: Greece", "C: Indonesia", "D: Peru"],
                    correctAnswer: "Greece"}]